package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private Integer CId;
    private String CName;
    private String CEmail;
    private byte CFlg;

    public Customer() {
    }

    public Customer(byte CFlg) {
        this.CFlg = CFlg;
    }

    public Customer(String CName, String CEmail, byte CFlg) {
        this.CName = CName;
        this.CEmail = CEmail;
        this.CFlg = CFlg;
    }

    public Integer getCId() {
        return this.CId;
    }

    public void setCId(Integer CId) {
        this.CId = CId;
    }

    public String getCName() {
        return this.CName;
    }

    public void setCName(String CName) {
        this.CName = CName;
    }

    public String getCEmail() {
        return this.CEmail;
    }

    public void setCEmail(String CEmail) {
        this.CEmail = CEmail;
    }

    public byte getCFlg() {
        return this.CFlg;
    }

    public void setCFlg(byte CFlg) {
        this.CFlg = CFlg;
    }

}
