package com.sabrac.processer.model;
// Generated Jul 12, 2017 9:59:20 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private Integer CId;
    private String CName;
    private String CEmail;
    private byte CFlg;
    private Set<Project> projects = new HashSet<Project>(0);

    public Customer() {
    }

    public Customer(byte CFlg) {
        this.CFlg = CFlg;
    }

    public Customer(String CName, String CEmail, byte CFlg, Set<Project> projects) {
        this.CName = CName;
        this.CEmail = CEmail;
        this.CFlg = CFlg;
        this.projects = projects;
    }

    public Integer getCId() {
        return this.CId;
    }

    public void setCId(Integer CId) {
        this.CId = CId;
    }

    public String getCName() {
        return this.CName;
    }

    public void setCName(String CName) {
        this.CName = CName;
    }

    public String getCEmail() {
        return this.CEmail;
    }

    public void setCEmail(String CEmail) {
        this.CEmail = CEmail;
    }

    public byte getCFlg() {
        return this.CFlg;
    }

    public void setCFlg(byte CFlg) {
        this.CFlg = CFlg;
    }

    public Set<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

}
