package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

    private Integer fbId;
    private Project project;
    private String fbTitle;
    private int fbType;
    private String fbDescription;
    private Integer fbStatus;
    private Date fbReceivedate;
    private Date fbSenddate;
    private Date fbDeadline;
    private byte fbFlg;

    public Feedback() {
    }

    public Feedback(Project project, int fbType, byte fbFlg) {
        this.project = project;
        this.fbType = fbType;
        this.fbFlg = fbFlg;
    }

    public Feedback(Project project, String fbTitle, int fbType, String fbDescription, Integer fbStatus,
            Date fbReceivedate, Date fbSenddate, Date fbDeadline, byte fbFlg) {
        this.project = project;
        this.fbTitle = fbTitle;
        this.fbType = fbType;
        this.fbDescription = fbDescription;
        this.fbStatus = fbStatus;
        this.fbReceivedate = fbReceivedate;
        this.fbSenddate = fbSenddate;
        this.fbDeadline = fbDeadline;
        this.fbFlg = fbFlg;
    }

    public Integer getFbId() {
        return this.fbId;
    }

    public void setFbId(Integer fbId) {
        this.fbId = fbId;
    }

    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getFbTitle() {
        return this.fbTitle;
    }

    public void setFbTitle(String fbTitle) {
        this.fbTitle = fbTitle;
    }

    public int getFbType() {
        return this.fbType;
    }

    public void setFbType(int fbType) {
        this.fbType = fbType;
    }

    public String getFbDescription() {
        return this.fbDescription;
    }

    public void setFbDescription(String fbDescription) {
        this.fbDescription = fbDescription;
    }

    public Integer getFbStatus() {
        return this.fbStatus;
    }

    public void setFbStatus(Integer fbStatus) {
        this.fbStatus = fbStatus;
    }

    public Date getFbReceivedate() {
        return this.fbReceivedate;
    }

    public void setFbReceivedate(Date fbReceivedate) {
        this.fbReceivedate = fbReceivedate;
    }

    public Date getFbSenddate() {
        return this.fbSenddate;
    }

    public void setFbSenddate(Date fbSenddate) {
        this.fbSenddate = fbSenddate;
    }

    public Date getFbDeadline() {
        return this.fbDeadline;
    }

    public void setFbDeadline(Date fbDeadline) {
        this.fbDeadline = fbDeadline;
    }

    public byte getFbFlg() {
        return this.fbFlg;
    }

    public void setFbFlg(byte fbFlg) {
        this.fbFlg = fbFlg;
    }

}
