package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

    private Integer MId;
    private String MName;
    private String MComment;
    private byte MFlg;
    private Set<Project> projects = new HashSet<Project>(0);
    private Set<ProjectMember> projectMembers = new HashSet<ProjectMember>(0);

    public Member() {
    }

    public Member(byte MFlg) {
        this.MFlg = MFlg;
    }

    public Member(String MName, String MComment, byte MFlg, Set<Project> projects, Set<ProjectMember> projectMembers) {
        this.MName = MName;
        this.MComment = MComment;
        this.MFlg = MFlg;
        this.projects = projects;
        this.projectMembers = projectMembers;
    }

    public Integer getMId() {
        return this.MId;
    }

    public void setMId(Integer MId) {
        this.MId = MId;
    }

    public String getMName() {
        return this.MName;
    }

    public void setMName(String MName) {
        this.MName = MName;
    }

    public String getMComment() {
        return this.MComment;
    }

    public void setMComment(String MComment) {
        this.MComment = MComment;
    }

    public byte getMFlg() {
        return this.MFlg;
    }

    public void setMFlg(byte MFlg) {
        this.MFlg = MFlg;
    }

    public Set<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

    public Set<ProjectMember> getProjectMembers() {
        return this.projectMembers;
    }

    public void setProjectMembers(Set<ProjectMember> projectMembers) {
        this.projectMembers = projectMembers;
    }

}
