package com.sabrac.processer.model;
// Generated Jul 12, 2017 9:59:20 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

    private Integer pjId;
    private Customer customer;
    private Status status;
    private Type type;
    private String pjName;
    private Integer pjCapacity;
    private Integer pjAsignee;
    private Date pjReceivedate;
    private Date pjSenddate;
    private Date pjDeadline;
    private String pjComment;
    private byte pjFlg;
    private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
    private Set<ProjectMember> projectMembers = new HashSet<ProjectMember>(0);

    public Project() {
    }

    public Project(Customer customer, String pjName, byte pjFlg) {
        this.customer = customer;
        this.pjName = pjName;
        this.pjFlg = pjFlg;
    }

    public Project(Customer customer, Status status, Type type, String pjName, Integer pjCapacity, Integer pjAsignee,
            Date pjReceivedate, Date pjSenddate, Date pjDeadline, String pjComment, byte pjFlg, Set<Feedback> feedbacks,
            Set<ProjectMember> projectMembers) {
        this.customer = customer;
        this.status = status;
        this.type = type;
        this.pjName = pjName;
        this.pjCapacity = pjCapacity;
        this.pjAsignee = pjAsignee;
        this.pjReceivedate = pjReceivedate;
        this.pjSenddate = pjSenddate;
        this.pjDeadline = pjDeadline;
        this.pjComment = pjComment;
        this.pjFlg = pjFlg;
        this.feedbacks = feedbacks;
        this.projectMembers = projectMembers;
    }

    public Integer getPjId() {
        return this.pjId;
    }

    public void setPjId(Integer pjId) {
        this.pjId = pjId;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Type getType() {
        return this.type;
    }

    public void setType(Type type) {
        this.type = type;
    }

    public String getPjName() {
        return this.pjName;
    }

    public void setPjName(String pjName) {
        this.pjName = pjName;
    }

    public Integer getPjCapacity() {
        return this.pjCapacity;
    }

    public void setPjCapacity(Integer pjCapacity) {
        this.pjCapacity = pjCapacity;
    }

    public Integer getPjAsignee() {
        return this.pjAsignee;
    }

    public void setPjAsignee(Integer pjAsignee) {
        this.pjAsignee = pjAsignee;
    }

    public Date getPjReceivedate() {
        return this.pjReceivedate;
    }

    public void setPjReceivedate(Date pjReceivedate) {
        this.pjReceivedate = pjReceivedate;
    }

    public Date getPjSenddate() {
        return this.pjSenddate;
    }

    public void setPjSenddate(Date pjSenddate) {
        this.pjSenddate = pjSenddate;
    }

    public Date getPjDeadline() {
        return this.pjDeadline;
    }

    public void setPjDeadline(Date pjDeadline) {
        this.pjDeadline = pjDeadline;
    }

    public String getPjComment() {
        return this.pjComment;
    }

    public void setPjComment(String pjComment) {
        this.pjComment = pjComment;
    }

    public byte getPjFlg() {
        return this.pjFlg;
    }

    public void setPjFlg(byte pjFlg) {
        this.pjFlg = pjFlg;
    }

    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

    public Set<ProjectMember> getProjectMembers() {
        return this.projectMembers;
    }

    public void setProjectMembers(Set<ProjectMember> projectMembers) {
        this.projectMembers = projectMembers;
    }

}
