package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

    private Integer pjId;
    private Member member;
    private Status status;
    private String pjName;
    private Integer pjType;
    private Integer pjCapacity;
    private Date pjReceivedate;
    private Date pjSenddate;
    private Date pjDeadline;
    private String pjComment;
    private byte pjFlg;
    private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
    private Set<ProjectMember> projectMembers = new HashSet<ProjectMember>(0);

    public Project() {
    }

    public Project(String pjName, byte pjFlg) {
        this.pjName = pjName;
        this.pjFlg = pjFlg;
    }

    public Project(Member member, Status status, String pjName, Integer pjType, Integer pjCapacity, Date pjReceivedate,
            Date pjSenddate, Date pjDeadline, String pjComment, byte pjFlg, Set<Feedback> feedbacks,
            Set<ProjectMember> projectMembers) {
        this.member = member;
        this.status = status;
        this.pjName = pjName;
        this.pjType = pjType;
        this.pjCapacity = pjCapacity;
        this.pjReceivedate = pjReceivedate;
        this.pjSenddate = pjSenddate;
        this.pjDeadline = pjDeadline;
        this.pjComment = pjComment;
        this.pjFlg = pjFlg;
        this.feedbacks = feedbacks;
        this.projectMembers = projectMembers;
    }

    public Integer getPjId() {
        return this.pjId;
    }

    public void setPjId(Integer pjId) {
        this.pjId = pjId;
    }

    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getPjName() {
        return this.pjName;
    }

    public void setPjName(String pjName) {
        this.pjName = pjName;
    }

    public Integer getPjType() {
        return this.pjType;
    }

    public void setPjType(Integer pjType) {
        this.pjType = pjType;
    }

    public Integer getPjCapacity() {
        return this.pjCapacity;
    }

    public void setPjCapacity(Integer pjCapacity) {
        this.pjCapacity = pjCapacity;
    }

    public Date getPjReceivedate() {
        return this.pjReceivedate;
    }

    public void setPjReceivedate(Date pjReceivedate) {
        this.pjReceivedate = pjReceivedate;
    }

    public Date getPjSenddate() {
        return this.pjSenddate;
    }

    public void setPjSenddate(Date pjSenddate) {
        this.pjSenddate = pjSenddate;
    }

    public Date getPjDeadline() {
        return this.pjDeadline;
    }

    public void setPjDeadline(Date pjDeadline) {
        this.pjDeadline = pjDeadline;
    }

    public String getPjComment() {
        return this.pjComment;
    }

    public void setPjComment(String pjComment) {
        this.pjComment = pjComment;
    }

    public byte getPjFlg() {
        return this.pjFlg;
    }

    public void setPjFlg(byte pjFlg) {
        this.pjFlg = pjFlg;
    }

    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

    public Set<ProjectMember> getProjectMembers() {
        return this.projectMembers;
    }

    public void setProjectMembers(Set<ProjectMember> projectMembers) {
        this.projectMembers = projectMembers;
    }

}
