package com.sabrac.processer.model;
// Generated Jul 12, 2017 9:59:20 AM by Hibernate Tools 5.2.3.Final

/**
 * ProjectMember generated by hbm2java
 */
public class ProjectMember implements java.io.Serializable {

    private Integer pmId;
    private Member member;
    private Project project;

    public ProjectMember() {
    }

    public ProjectMember(Member member, Project project) {
        this.member = member;
        this.project = project;
    }

    public Integer getPmId() {
        return this.pmId;
    }

    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    public Member getMember() {
        return this.member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

}
