package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

    private Integer TId;
    private String TName;
    private byte TFlg;

    public Type() {
    }

    public Type(byte TFlg) {
        this.TFlg = TFlg;
    }

    public Type(String TName, byte TFlg) {
        this.TName = TName;
        this.TFlg = TFlg;
    }

    public Integer getTId() {
        return this.TId;
    }

    public void setTId(Integer TId) {
        this.TId = TId;
    }

    public String getTName() {
        return this.TName;
    }

    public void setTName(String TName) {
        this.TName = TName;
    }

    public byte getTFlg() {
        return this.TFlg;
    }

    public void setTFlg(byte TFlg) {
        this.TFlg = TFlg;
    }

}
