package com.sabrac.processer.model;
// Generated Jul 12, 2017 9:59:20 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4361723082521239493L;

    private Integer TId;
    private String TName;
    private byte TFlg;
    private Set<Project> projects = new HashSet<Project>(0);
    private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

    public Type() {
    }

    public Type(byte TFlg) {
        this.TFlg = TFlg;
    }

    public Type(String TName, byte TFlg, Set<Project> projects, Set<Feedback> feedbacks) {
        this.TName = TName;
        this.TFlg = TFlg;
        this.projects = projects;
        this.feedbacks = feedbacks;
    }

    public Integer getTId() {
        return this.TId;
    }

    public void setTId(Integer TId) {
        this.TId = TId;
    }

    public String getTName() {
        return this.TName;
    }

    public void setTName(String TName) {
        this.TName = TName;
    }

    public byte getTFlg() {
        return this.TFlg;
    }

    public void setTFlg(byte TFlg) {
        this.TFlg = TFlg;
    }

    public Set<Project> getProjects() {
        return this.projects;
    }

    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }

    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }

}
