package com.sabrac.processer.model;
// Generated Jul 3, 2017 3:14:44 PM by Hibernate Tools 5.2.3.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer UId;
    private String UUsername;
    private String UPassword;
    private int URole;
    private byte UFlg;

    public User() {
    }

    public User(String UUsername, String UPassword, int URole, byte UFlg) {
        this.UUsername = UUsername;
        this.UPassword = UPassword;
        this.URole = URole;
        this.UFlg = UFlg;
    }

    public Integer getUId() {
        return this.UId;
    }

    public void setUId(Integer UId) {
        this.UId = UId;
    }

    public String getUUsername() {
        return this.UUsername;
    }

    public void setUUsername(String UUsername) {
        this.UUsername = UUsername;
    }

    public String getUPassword() {
        return this.UPassword;
    }

    public void setUPassword(String UPassword) {
        this.UPassword = UPassword;
    }

    public int getURole() {
        return this.URole;
    }

    public void setURole(int URole) {
        this.URole = URole;
    }

    public byte getUFlg() {
        return this.UFlg;
    }

    public void setUFlg(byte UFlg) {
        this.UFlg = UFlg;
    }

}
